# Site settings
title: Neo Elemento
email: vishnu.aol27@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of Vishnu Padmanabhan - Full Stack developer focusing on JavaScript and PHP.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://neoelemento.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title

paginate: 7