# Site settings
title: neoelemento
owner: Vishnu Padmanabhan
email: vishnu@neoelemento.com
description: > # this means to ignore newlines until "baseurl:"
  I am a full stack developer who loves building apps in JavaScript and PHP. I am very keen on keeping up with technology and will be using this blog as a platform to get my ideas and expertise out there.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://neoelemento.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento

# Build settings
markdown: kramdown
sass:
    style: compressed
gems:
  - jemoji

permalink: /:year/:month/:day/:title/

paginate: 10