# Site settings
title: neoelemento
owner: Vishnu Padmanabhan
email: vishnu@neoelemento.com
description: > # this means to ignore newlines until "baseurl:"
  neoelemento is a pubication curated by Vishnu Padmanabhan. It is a collection of articles & tips.
disclaimer: >
  The content of this website is solely the opinion of the writer.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://neoelemento.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
    style: compressed
gems:
  - jemoji
  - jekyll-paginate

permalink: /:year/:month/:day/:title/
future: true
paginate: 12